# conf/model/sac_discrete.yaml
_target_: elegantrl.agents.AgentModSACDiscrete  # 指向你 Agent 类的全路径
agent_name: "AgentModSACDiscrete"
if_off_policy: true
target_entropy: null
critic_tau: 0.995
criterion:
    _target_: torch.nn.SmoothL1Loss           # 目标类的完整路径
    reduction: "none"
actor_learning_rate: 1e-04
critic_learning_rate: 1e-04
alpha_learning_rate: 1e-04

# 1. Actor 配置
actor:
  type: "mlp"
  temp_tau: 1.0
  greedy_eps: 0.15
  K: ${env.K}
  tcn_args:
    net_dims: [256, 128]
    emb_ch: 64
    num_blocks: 3
    kernel_size: 3
    dilations: [1, 2, 4]
    dropout: 0.0
  mlp_args:
    net_dims: [128, 256, 128, 32]
    use_ln: false

# 2. Critic 配置
critic:
  type: "mlp"
  num_ensembles: 8
  state_noise_std: 0.00
  K: ${env.K}
  tcn_args:
    net_dims: [256, 128]
    emb_ch: 64
    num_blocks: 3
    kernel_size: 3
    dilations: [1, 2, 4]
    dropout: 0.0
  mlp_args:
    net_dims: [128,256, 128, 32]