# conf/model/reinforce.yaml
_target_: elegantrl.agents.AgentReinforce
agent_name: "AgentReinforce"
if_off_policy: false

# 1. 核心算法参数 (对应 AgentReinforce.__init__)
mode: "multicase"        # 模式选择: "singlecase" 或 "multicase"
ratio_clip: 0.25         # PPO Clip 阈值
lambda_entropy: 0.01     #! 熵正则化系数 (无Critic时建议调小，防止过度随机)
repeat_times: 2          # 同一批数据的循环训练次数 (Epochs)
actor_learning_rate: 1e-04
criterion:
    _target_: torch.nn.MSELoss           # 目标类的完整路径
    reduction: "none"
baseline_alpha: 0.05 #! 控制ema速率
# 注意：Reinforce 纯策略梯度不需要 critic_learning_rate, criterion, lambda_gae 等参数

# 2. Actor 网络配置 (对应 ActorDiscreteReinforce)
actor:
  type: "mlp"
  temp_tau: 1.0          # Softmax 温度系数 (控制采样分布的平滑度)
  greedy_eps: 0.05       # Epsilon-Greedy (建议设小或为0，主要依赖分布采样探索)
  mlp_args:
    net_dims: [128, 128, 32] # 网络层宽
    use_ln: false        # 是否使用 LayerNorm