env: &env_config
  env_name: "AStockExecutionEnv"                  # 环境名称
  _target_: elegantRL.envs.AStockExecutionEnv.AStockExecutionEnv  # 指向环境类的完整路径
  meta_dir: "/home/songrui.wang/data/meta_date"
  case_dir: "/home/songrui.wang/data/case_2"
  #train_start: "2024-04-01"
  #train_end: "2024-04-18"
  #test_start: "2024-06-04"
  #test_end: "2024-06-07"
  train_date_list_path: "/home/songrui.wang/RL_training/conf/date/1day.txt"
  test_date_list_path: "/home/songrui.wang/RL_training/conf/date/1day.txt"
  mode: "train"                            # 环境模式 (train/test)
  action_mapping:
    0: 0.0
    1: 0.02
    2: 0.04
    3: 0.06
    4: 0.08
  eval_num_workers: 16                   # 评估时的并行环境数量
  sample_method: "seq"                       #! 采样方法 (random/seq/weighted) 测试环境里必须的
  num_envs: 1                          # 向量化子环境数量 (1为单环境, >1为向量化环境)
  max_step: 99999                        # 每个 Episode 的最大步数
  state_dim: 30                        #? 状态维度 (Python 代码中会根据 K 计算)
  action_dim: 5                          # 动作维度
  lambda_decay: 0.04
  if_discrete: true                      #! 是否为离散动作空间
  gpu_id: -1
  noise_std_ratio: 0.0 #! 正则其二
  # --- 自定义环境参数 ---
  if_build_vec_env: false                # 是否强制构建 VecEnv
  K: 1                                  # 历史数据窗口长度
  padding0: false                        # 是否进行 0 填充
  impact_threshold: 0.0002                   # 价格冲击阈值 (根据实际情况调整)
  signal_norm_threshold: 0.00                  # 信号归一化阈值 (根据实际情况调整)
  signal_impact_k: 1.0
  signal_1m_row_offset: 0.00
  vol_level1_threshold_p: 0.0
  if_save_log: false
  save_name: "reinforce_04_14"